apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  db-name: "much_todo_db"
  jwt-expiration-hours: "72"
  enable-cache: "true"
  log-level: "info"
  log-format: "json"
  secure-cookie: "true"
  cookie-domains: "d1rikn573d83tp.cloudfront.net"
  allowed-origins: "https://d1rikn573d83tp.cloudfront.net"
